# Generated by Django 3.1.1 on 2020-12-15 07:17

import customer.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import seller.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('phone_num', models.CharField(max_length=10, validators=[seller.validators.phone_validation])),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to=customer.models.get_image_path)),
                ('dob', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
