# Generated by Django 3.1.1 on 2020-12-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_namuna_falful',
            field=models.BooleanField(default=False, verbose_name='Namuna Falful'),
        ),
    ]
