# Generated by Django 3.1.1 on 2021-01-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.CharField(blank=True, choices=[('select option', 'Select Option'), ('In Stock', 'In Stock'), ('Out Of Stock', 'Out Of Stock')], default='Select Option', max_length=20, null=True),
        ),
    ]
