# Generated by Django 3.1.1 on 2021-01-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_organic_store',
            field=models.BooleanField(default=False, verbose_name='Item  From Organic Store'),
        ),
    ]
