# Generated by Django 3.1.1 on 2021-01-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='image',
            field=models.ImageField(null=True, upload_to='img/campaign/'),
        ),
    ]
