# Generated by Django 3.1.1 on 2020-12-15 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import seller.models
import seller.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=100)),
                ('supplier_email', models.EmailField(max_length=254)),
                ('supplier_phone_num', models.CharField(max_length=10, validators=[seller.validators.phone_validation])),
                ('shop_name', models.CharField(max_length=100)),
                ('shop_address', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('accept', 'Accept'), ('ignore', 'Ignore')], default='waiting', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('about_me', models.TextField()),
                ('shop_name', models.CharField(max_length=50)),
                ('phone_num', models.CharField(max_length=10, validators=[seller.validators.phone_validation])),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to=seller.models.get_image_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
