# Generated by Django 3.1.1 on 2020-12-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('delivered', 'Delivered'), ('refunded', 'Refunded')], default='created', max_length=30),
        ),
    ]
